[project]
name = "expense-tracker"
version = "0.1.0"
description = "A simple personal expense tracker"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "pydantic-settings>=2.10.1",
]

[dependency-groups]
dev = [
    "uvicorn>=0.35.0",
]
